-- Generated by scripts/hypr2lua.
-- Source: /home/hancore/.config/omarchy/themes/greek-noir/hyprland.conf

hl.config({
  general = {
    col = {
      active_border = "rgb(706e5e)",
      inactive_border = "rgb(171717)",
    },
    border_size = 3,
    gaps_in = 5,
    gaps_out = 5,
  },
  decoration = {
    rounding = 4,
    rounding_power = 3,
    shadow = {
      enabled = true,
      render_power = 8,
      range = 8,
      color = "rgba(22,22,22, 0.5)",
    },
  },
})
